/*
 * generated by Xtext
 */
package schlingel.bplaced.net.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLSGLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(schlingel.bplaced.net.lSGL.LSGLPackage.eINSTANCE);
		return result;
	}
}
