/*
* generated by Xtext
*/
package schlingel.bplaced.net;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LSGLStandaloneSetup extends LSGLStandaloneSetupGenerated{

	public static void doSetup() {
		new LSGLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

