/*
 * generated by Xtext
 */
package schlingel.bplaced.net;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LSGLRuntimeModule extends schlingel.bplaced.net.AbstractLSGLRuntimeModule {

}
