/**
 * generated by Xtext
 */
package schlingel.bplaced.net.validation;

import schlingel.bplaced.net.validation.AbstractLSGLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class LSGLValidator extends AbstractLSGLValidator {
}
