/**
 * generated by Xtext
 */
package schlingel.bplaced.net.generator;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import schlingel.bplaced.net.generator.model.LSGLModelGenerator;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class LSGLGenerator implements IGenerator {
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    final LSGLModelGenerator entityGenerator = new LSGLModelGenerator();
    entityGenerator.doGenerate(resource, fsa);
  }
}
