/*
* generated by Xtext
*/
package schlingel.bplaced.net.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import schlingel.bplaced.net.services.LSGLGrammarAccess;

public class LSGLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LSGLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected schlingel.bplaced.net.parser.antlr.internal.InternalLSGLParser createParser(XtextTokenStream stream) {
		return new schlingel.bplaced.net.parser.antlr.internal.InternalLSGLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public LSGLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LSGLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
