/*
* generated by Xtext
*/
package schlingel.bplaced.net.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LSGLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("schlingel/bplaced/net/parser/antlr/internal/InternalLSGL.tokens");
	}
}
